version: "3.5"

services:
  mysql:
    build: ./mysql
    ports:
      - target: 3306
        published: 3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    networks:
      - my-net

  server:
    build: ./
    ports:
      - target: 3000
        published: 3000
    restart: on-failure
    networks:
      - my-net
    depends_on:
      - mysql

networks:
  my-net: